insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (1, 'Max', 'López', 'Ramírez', '79947302T', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (2, 'Max', 'González', 'Fernández', '42255685F', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (3, 'Leo', 'Ramírez', 'García', '63187543L', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (4, 'Sophie', 'Rodríguez', 'González', '86729148X', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (5, 'Bella', 'Martínez', 'Ramírez', '26652124P', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (6, 'Rocky', 'Diaz', 'García', '49003959I', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (7, 'Bella', 'González', 'Pérez', '19873399S', 'Bigender');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (8, 'Oliver', 'González', 'García', '82545679K', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (9, 'Rocky', 'Pérez', 'Martínez', '36697827A', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (10, 'Oliver', 'Pérez', 'Torres', '94952349L', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (11, 'Rocky', 'Martínez', 'López', '04602260N', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (12, 'Mia', 'Diaz', 'Martínez', '25461535L', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (13, 'Max', 'López', 'Ramírez', '08381228E', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (14, 'Mia', 'López', 'García', '25672459A', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (15, 'Luna', 'López', 'Fernández', '22590924T', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (16, 'Luna', 'Diaz', 'García', '83122223K', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (17, 'Bella', 'Flores', 'Martínez', '15762122L', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (18, 'Oliver', 'Martínez', 'Ramírez', '27935048U', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (19, 'Leo', 'López', 'Ramírez', '90929425U', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (20, 'Rocky', 'Flores', 'Torres', '64589677D', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (21, 'Oliver', 'Ramírez', 'Fernández', '48279994R', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (22, 'Bella', 'Diaz', 'López', '18359241J', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (23, 'Rocky', 'Sánchez', 'De Luque', '80353937B', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (24, 'Oliver', 'Rodríguez', 'Torres', '42011356H', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (25, 'Rocky', 'Flores', 'López', '30946965M', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (26, 'Bella', 'Flores', 'Martínez', '90805383Z', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (27, 'Sophie', 'Rodríguez', 'Fernández', '40928521Q', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (28, 'Leo', 'Flores', 'González', '65285646Q', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (29, 'Rocky', 'Martínez', 'Pérez', '58071069I', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (30, 'Mia', 'Martínez', 'González', '34609834L', 'Non-binary');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (31, 'Mia', 'Torres', 'García', '73221243I', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (32, 'Charlie', 'Martínez', 'Ramírez', '03424521G', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (33, 'Bella', 'Pérez', 'De Luque', '02358447D', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (34, 'Charlie', 'Sánchez', 'González', '11799319J', 'Non-binary');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (35, 'Rocky', 'Ramírez', 'Pérez', '41568277O', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (36, 'Mia', 'Pérez', 'Pizjuan', '05154464B', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (37, 'Mia', 'Diaz', 'García', '70176352Z', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (38, 'Rocky', 'Pérez', 'González', '74960823I', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (39, 'Max', 'Diaz', 'Ramírez', '92817681R', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (40, 'Bella', 'Flores', 'López', '26619766K', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (41, 'Luna', 'Torres', 'Torres', '38665989V', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (42, 'Mia', 'González', 'Martínez', '42155025C', 'Agender');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (43, 'Charlie', 'Diaz', 'García', '28773512Y', 'Male');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (44, 'Leo', 'Sánchez', 'De Luque', '95776709B', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (45, 'Sophie', 'López', 'De Luque', '81876611N', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (46, 'Bella', 'Martínez', 'De Luque', '00140075I', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (47, 'Rocky', 'Torres', 'Martínez', '15353268R', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (48, 'Lucy', 'Pérez', 'De Luque', '89444989N', 'Female');
insert into empleado (id, nombre, apellido1, apellido2, dni, genero) values (49, 'Mia', 'Torres', 'Fernández', '23839093L', 'Male');

ALTER SEQUENCE empleado_seq RESTART WITH (49);